# Generated by Django 3.2.13 on 2022-07-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('library', models.CharField(max_length=100, verbose_name='libreria')),
                ('iframe', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'podcast',
                'verbose_name_plural': 'podcasts',
            },
        ),
    ]
