# Generated by Django 3.2.13 on 2022-07-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='library',
        ),
    ]
