# Generated by Django 3.2.13 on 2022-07-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_podcast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcast',
            options={'verbose_name': 'podcast', 'verbose_name_plural': 'podcasts'},
        ),
        migrations.AlterField(
            model_name='podcast',
            name='library',
            field=models.CharField(max_length=100, verbose_name='libreria'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
    ]
