# Generated by Django 3.2.13 on 2022-07-05 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20220704_0911'),
        ('posts', '0004_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('iframe', models.CharField(max_length=1000)),
                ('writer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='books.writer')),
            ],
            options={
                'verbose_name': 'entrevista',
                'verbose_name_plural': 'entrevistas',
            },
        ),
    ]
