# Generated by Django 3.2.13 on 2022-07-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='iframe',
            field=models.CharField(max_length=5000),
        ),
    ]
