# Generated by Django 3.2.13 on 2022-07-06 00:51

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_auto_20220704_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_post',
            options={'verbose_name': 'entrada', 'verbose_name_plural': 'entradas'},
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='date_published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fecha de publucación'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='oculto'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='status',
            field=models.CharField(choices=[('DRAFTED', 'Draft'), ('PUBLISHED', 'Publish')], default='DRAFT', max_length=10, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='subtítulo'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
    ]
