# Generated by Django 3.2.13 on 2022-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfiles'},
        ),
        migrations.AddField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_image', verbose_name='avatar'),
        ),
    ]
