# Generated by Django 3.2.13 on 2022-06-26 18:54

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=500)),
                ('year_published', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_approved', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('bio', models.CharField(help_text='Agrega información sobre este/a autor/a', max_length=2000)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('twitter_url', models.CharField(blank=True, default='#', help_text='Ingresa # si el escritor/a no posee una cuenta', max_length=250, null=True)),
                ('instagram_url', models.CharField(blank=True, default='#', help_text='Ingresa # si el escritor/a no posee una cuenta', max_length=250, null=True)),
                ('web_url', models.URLField()),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
            },
        ),
    ]
