# Generated by Django 3.2.13 on 2022-07-03 14:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_approved', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('lastname', models.CharField(max_length=100)),
                ('bio', ckeditor.fields.RichTextField(help_text='Agrega información sobre este/a autor/a')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('twitter_url', models.CharField(blank=True, default='#', help_text='Ingresa # si el escritor/a no posee una cuenta', max_length=250, null=True)),
                ('instagram_url', models.CharField(blank=True, default='#', help_text='Ingresa # si el escritor/a no posee una cuenta', max_length=250, null=True)),
                ('web_url', models.URLField(blank=True, verbose_name='Web Oficial')),
                ('image', models.ImageField(blank=True, null=True, upload_to='writers-gallery')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
                'unique_together': {('name', 'lastname')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=500)),
                ('year_published', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.category')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
            },
        ),
    ]
