# Generated by Django 3.2.13 on 2022-07-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='image',
            field=models.ImageField(blank=True, default='writers-gallery/default.jpg', null=True, upload_to='writers-gallery'),
        ),
    ]
