# Generated by Django 3.2.13 on 2022-06-26 23:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Agrega información sobre este/a autor/a'),
        ),
    ]
