# Generated by Django 3.2.13 on 2022-07-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_writer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='image',
            field=models.ImageField(blank=True, default='media/writers-gallery/default.jpg', null=True, upload_to='writers-gallery'),
        ),
    ]
