# Generated by Django 3.2.13 on 2022-07-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_writer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='image',
            field=models.ImageField(default='media/writers-gallery/default.jpg', upload_to='writers-gallery'),
        ),
    ]
