# Generated by Django 3.2.13 on 2022-06-30 00:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_writer_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='writer',
            name='bio',
            field=ckeditor.fields.RichTextField(help_text='Agrega información sobre este/a autor/a'),
        ),
    ]
