# Generated by Django 3.2.13 on 2022-06-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20220629_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
    ]
