# Generated by Django 3.2.13 on 2022-06-30 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_writer_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='nombre',
            new_name='name',
        ),
    ]
