# Generated by Django 3.2.13 on 2022-07-04 11:10

import ckeditor.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_writer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='twitter_url',
        ),
        migrations.AlterField(
            model_name='writer',
            name='bio',
            field=ckeditor.fields.RichTextField(verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='writers-gallery', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='web_url',
            field=models.URLField(blank=True, verbose_name='web oficial'),
        ),
    ]
