# Generated by Django 3.2.13 on 2022-07-04 12:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20220704_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='no-cover-available.jpg', upload_to='books-cover-gallery', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='bio',
            field=ckeditor.fields.RichTextField(verbose_name='biografía'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='writers-gallery', verbose_name='fotografía'),
        ),
    ]
